{% set version = "0.7.0" %}

package:
  name: pythonfmu
  version: {{ version }}

source:
  url: https://github.com/NTNU-IHB/PythonFMU/archive/refs/tags/v{{ version }}.tar.gz
  sha256: caafdfcbd08e57e5d913b94e5be87f9727f82825bebf6cec495f6efedba97ebf
  patches:
    - clang.patch

build:
  number: 0
  python_version_independent: true  # [is_abi3]
  skip: true  # [is_abi3 and not is_python_min]
  entry_points:
    - pythonfmu = pythonfmu.__main__:cli_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - python-abi3  # [is_abi3]
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
    - pyfmi
  commands:
    - pytest --pyargs pythonfmu.tests -k "not multiple_fmus_pyfmi"
  imports:
    - pythonfmu

about:
  home: https://github.com/NTNU-IHB/PythonFMU
  summary: A lightweight framework that enables the packaging of Python3.x code as co-simulation FMUs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/NTNU-IHB/PythonFMU

extra:
  recipe-maintainers:
    - fcollonval
    - markaren
    - jschueller
