{% set name = "pythonfmu" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4afb4f5bd6eefbf6b3cff6814373b4f9250d4c41ad4a612aec4e5c6b5e4ef58b

build:
  number: 0
  skip: true  # [py<36 or osx]
  entry_points:
    - pythonfmu-builder = pythonfmu.builder:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - pyfmi
  commands:
    - pytest --pyargs pythonfmu.tests
  imports:
    - pythonfmu

about:
  home: https://github.com/NTNU-IHB/PythonFMU
  summary: A lightweight framework that enables the packaging of Python3.x code as co-simulation FMUs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/NTNU-IHB/PythonFMU

extra:
  recipe-maintainers:
    - fcollonval
    - markaren
