{% set name = "pythonfmu" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be93463ed61eee679ad273cb031f3b6087cc4ddc096300526f0b7b85716c1ca6

build:
  number: 1
  entry_points:
    - pythonfmu = pythonfmu.__main__:cli_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - pyfmi
  commands:
    - pytest --pyargs pythonfmu.tests -k "not multiple_fmus_pyfmi"
  imports:
    - pythonfmu

about:
  home: https://github.com/NTNU-IHB/PythonFMU
  summary: A lightweight framework that enables the packaging of Python3.x code as co-simulation FMUs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/NTNU-IHB/PythonFMU

extra:
  recipe-maintainers:
    - fcollonval
    - markaren
