{% set name = "pythonfmu" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e531462c9983da3bbd95e813d8c6c6eac9de3171dae9621436538cff7643a9bf

build:
  number: 0
  skip: true  # [osx]
  entry_points:
    - pythonfmu = pythonfmu.__main__:cli_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
    - pyfmi
  commands:
    - pytest --pyargs pythonfmu.tests -k "not multiple_fmus_pyfmi"
  imports:
    - pythonfmu

about:
  home: https://github.com/NTNU-IHB/PythonFMU
  summary: A lightweight framework that enables the packaging of Python3.x code as co-simulation FMUs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/NTNU-IHB/PythonFMU

extra:
  recipe-maintainers:
    - fcollonval
    - markaren
